### PR TITLE
Clarify engine_version for Aurora Postgres

### PR DESCRIPTION
**Pull request by FelisiaM**
Which other branches should this be merged with (if any)?
* main
* 1.3

### CODE REVIEW

**Comment by RichardJJG** [comment]
Thanks, @FelisiaM

**Comment by zucchinidev** [comment]
Hello @RichardJJG, I see that these changes have not been added to the branch 1.3.0. Could we add and publish it?

**Comment by RichardJJG** [comment]
Hi,  @zucchinidev, we have a [Tracker story](https://www.pivotaltracker.com/story/show/183815376) in the queue. That said, there are only two writers for all of Tanzu Services -- we can't publish every PR within 24 hours of merging it, I'm afraid. I'll see about doing it today.

**Comment by zucchinidev** [comment]
My apologies @RichardJJG, I thought it could be an oversight or a mistake. Of course, there is no rush to publish it

**Comment by RichardJJG** [comment]
@zucchinidev, I'm cherry-picking to 1.3 and I've noticed I can't properly do so because [the version number is very different](https://github.com/pivotal-cf/docs-csb-aws/blob/1.3/reference/aws-aurora-postgresql.html.md.erb#L125). If you want me to change the example version number to `14.4`, let me know.

**Comment by FelisiaM** [comment]
@RichardJJG The previous version number is incorrect. 
Changing it to 14.4 is the right thing to do.

Thanks

**Pull request merged**
