### PR TITLE
Update redis and postgres

### PR DESCRIPTION
**Pull request by FelisiaM**
Which other branches should this be merged with (if any)?
* main
* 1.1

### CODE REVIEW

**Comment by RichardJJG** [comment]
Thanks!

**Comment by RichardJJG** [comment]
@FelisiaM, are the maintenance start and end times really strings and not integers? I'm talking about lines such as [this one](https://github.com/pivotal-cf/docs-csb-aws/pull/43/files#diff-13e9c5b9f9fe1d75eec96ced39a79b76a6cbeb1cc752047c5d8b60040a342ce5R170).

**Comment by RichardJJG** [comment]
@FelisiaM, is the `0` deliberate in [this line](https://github.com/pivotal-cf/docs-csb-aws/pull/43/files#diff-75b4a6768f5b2e3955483f0de85549567f9df94ce8bad53c3f488916280d9c9aR191)?

**Comment by FelisiaM** [comment]
@RichardJJG  
- the maintenance start/end times are indeed strings
- is the 0 in [this line](https://github.com/pivotal-cf/docs-csb-aws/pull/43/files#diff-75b4a6768f5b2e3955483f0de85549567f9df94ce8bad53c3f488916280d9c9aR191) is an accident 
Thanks for looking into this.

**Pull request merged**
